W6D5/ninety_nine_cats/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

    resources :cats, only: [:index, :show]



end
#      Prefix Verb URI Pattern                                                                              Controller#Action
#                      cats GET  /cats(.:format)                                                                          cats#index
#                       cat GET  /cats/:id(.:format)                                                                      cats#show
#        rails_service_blob GET  /rails/active_storage/blobs/:signed_id/*filename(.:format)                               active_storage/blobs#show
# rails_blob_representation GET  /rails/active_storage/representations/:signed_blob_id/:variation_key/*filename(.:format) active_storage/representations#show
#        rails_disk_service GET  /rails/active_storage/disk/:encoded_key/*filename(.:format)                              active_storage/disk#show
# update_rails_disk_service PUT  /rails/active_storage/disk/:encoded_token(.:format)                                      active_storage/disk#update
#      rails_direct_uploads POST /rails/active_storage/direct_uploads(.:format)                                           active_storage/direct_uploads#create

W6D5/ninety_nine_cats/app/models/cat.rb
class Cat < ApplicationRecord

  COLORS = %w(black white gray orange brown)

  validates :birth_date, :color, :name, :sex, presence: true 
  validates :color, inclusion: { in: COLORS }
  validates :sex, inclusion: { in: ['M', 'F'] }
 


end 

W6D5/ninety_nine_cats/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

W6D5/ninety_nine_cats/app/controllers/cats_controller.rb
class CatsController < ApplicationController 

  def index 
      @cats = Cat.all
      render :index 
  end 

  def show  
      @cat = Cat.find_by(id: params[:id])
      if @cat
        render :show
      else 
        redirect_to cats_url
      end
  end 

  

end 

W6D5/ninety_nine_cats/app/views/cats/_form.html.erb
<form action= "/cats" method= "post">
  
  <label>Name
    <input type="text" name="cat[name]" value="<%= cat.name %>">
  </label>
  <br>
  <label>Sex
    <input type="radio" name="cat[sex]" value="M" <%= cat.sex == "M" ? "checked" : "" %> > Male
    <input type="radio" name="cat[sex]" value="F" <%= cat.sex == "F" ? "checked" : "" %>> Female
  </label>
  <br>
  <label>Birth Date
    <input type="date" name="cat[birth_date]" value="<%= cat.birth_date %>">
  </label>
  <br>
    <label>Color
    <select name="cat[color]">
     <option <%= type == :edit ? "disabled" : "selected" %>>--Choose a Color--</option>

    </select>
     </label>

W6D5/ninety_nine_cats/app/views/cats/index.html.erb
<h1>  All The Cats    </h1>

<ul>
  <% @cats.each do |cat| %> 
    <li>
      <a href= '<%= cat_url(cat) %>'> <%= cat.name %> </a>
    </li>
  <% end %>
</ul>

W6D5/ninety_nine_cats/app/views/cats/new.html.erb
<%= render 'form' %>

W6D5/ninety_nine_cats/app/views/cats/show.html.erb
<html>
<head>
<style>

table, th, td {
  border: 1px solid black;
}
</style>
</head>
<body>

<h1><% @cat.name %> </h1>

<table>
  <tr>
    <th style="height:100px"> Cat Birthday </th>
    <th style="height:100px"> Cat Sex </th>
    <th style="height:100px"> Cat Color </th>
    <th style="height:100px"> Cat Description </th>
  </tr>
  <tr>
    <td><%= @cat.birth_date %></td>
    <td><%= @cat.sex %></td>
    <td><%= @cat.color %></td>
    <td><%= @cat.description %></td>
    
  </tr>
  <tr>
    <td> other birth info </td>
    <td> sex change maybe? </td>
    <td> I wanted to be white  </td>
    <td> fluffy and playful </td>
  </tr>
</table>

W6D5/ninety_nine_cats/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NinetyNineCats</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>